services:
  api:
    build: .
    image: jsonapilatest
    networks:
      - appnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


networks:
  appnet:
    driver: bridge
